name: shipin下载九次rclone上传.yml
on:
  workflow_dispatch:
    inputs:
      path:
        description: '下载路径'
        required: true
        default: 'shipin'

jobs:
  pikpak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create Config'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml
      - name: update
        run: |
           sudo apt-get update >/dev/null 2>&1
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
           tool-cache: true
           android: true
           dotnet: true
           haskell: true
           large-packages: true
           docker-images: false
           swap-storage: true

      - name: 'Download file from PikPak 1'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_1 }}

      - name: upload onedrive 1
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_1 }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.YEARS }}/${{ secrets.VIDEO_ANIME_SAVE_DIRECTORY }}   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}
          
      - name: Delete downloaded files 1
        run: |
         sudo rm -rf ${{ github.workspace }}/${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_1 }}/
         
         
         
         sudo rm -rf ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_1 }}/

      - uses: actions/checkout@v2
      - name: 'Create Config 2'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml

      - name: 'Download file from PikPak 2'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_2 }}

      - name: upload onedrive 2
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_2 }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.YEARS }}/${{ secrets.VIDEO_ANIME_SAVE_DIRECTORY }}   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}

      - name: Delete downloaded files 2
        run: |
         sudo rm -rf ${{ github.workspace }}/${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_2 }}/
         
         
         
         sudo rm -rf ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_2 }}/

      - uses: actions/checkout@v2
      - name: 'Create Config 3'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml

      - name: 'Download file from PikPak 3'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_3 }}

      - name: upload onedrive 3
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_3 }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.YEARS }}/${{ secrets.VIDEO_ANIME_SAVE_DIRECTORY }}   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}

      - name: Delete downloaded files 3
        run: |
         sudo rm -rf ${{ github.workspace }}/${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_3 }}/
         
         
         
         sudo rm -rf ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_3 }}/ 

      - uses: actions/checkout@v2
      - name: 'Create Config 4'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml

      - name: 'Download file from PikPak 4'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_4 }}

      - name: upload onedrive 4
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_4 }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.YEARS }}/${{ secrets.VIDEO_ANIME_SAVE_DIRECTORY }}   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}

      - name: Delete downloaded files 4
        run: |
         sudo rm -rf ${{ github.workspace }}/${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_4 }}/
         
         
         
         sudo rm -rf ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_4 }}/

      - uses: actions/checkout@v2
      - name: 'Create Config 5'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml

      - name: 'Download file from PikPak 5'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_5 }}

      - name: upload onedrive 5
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_5 }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.YEARS }}/${{ secrets.VIDEO_ANIME_SAVE_DIRECTORY }}   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}

      - name: Delete downloaded files 5
        run: |
         sudo rm -rf ${{ github.workspace }}/${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_5 }}/
         
         
         
         sudo rm -rf ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_5 }}/  


      - uses: actions/checkout@v2
      - name: 'Create Config 6'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml

      - name: 'Download file from PikPak 6'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_6 }}

      - name: upload onedrive 6
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_6 }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.YEARS }}/${{ secrets.VIDEO_ANIME_SAVE_DIRECTORY }}   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}

      - name: Delete downloaded files 6
        run: |
         sudo rm -rf ${{ github.workspace }}/${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_6 }}/
         
         
         
         sudo rm -rf ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_6 }}/  

      - uses: actions/checkout@v2
      - name: 'Create Config 7'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml

      - name: 'Download file from PikPak 7'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_7 }}

      - name: upload onedrive 7
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_7 }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.YEARS }}/${{ secrets.VIDEO_ANIME_SAVE_DIRECTORY }}   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}

      - name: Delete downloaded files 7
        run: |
         sudo rm -rf ${{ github.workspace }}/${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_7 }}/
         
         
         
         sudo rm -rf ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_7 }}/  


      - uses: actions/checkout@v2
      - name: 'Create Config 8'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml

      - name: 'Download file from PikPak 8'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_8 }}

      - name: upload onedrive 8
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_8 }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.YEARS }}/${{ secrets.VIDEO_ANIME_SAVE_DIRECTORY }}   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}

      - name: Delete downloaded files 8
        run: |
         sudo rm -rf ${{ github.workspace }}/${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_8 }}/
         
         
         
         sudo rm -rf ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_8 }}/   

      - uses: actions/checkout@v2
      - name: 'Create Config 9'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml

      - name: 'Download file from PikPak 9'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_9 }}

      - name: upload onedrive 9
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_9 }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.YEARS }}/${{ secrets.VIDEO_ANIME_SAVE_DIRECTORY }}   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}

      - name: Delete downloaded files 9
        run: |
         sudo rm -rf ${{ github.workspace }}/${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_9 }}/
         
         
         
         sudo rm -rf ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_9 }}/     
      - name: 删除旧的上传记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
