name: test单次.yml
on:
  workflow_dispatch:
    inputs:
      path:
        description: '下载路径'
        required: true
        default: 'test'

jobs:
  pikpak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create Config'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml

      - name: '1Download file from PikPak'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ github.event.inputs.path }}

      - name: upload onedrive
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ github.event.inputs.path }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.YEARS }}/${{ secrets.TEST_ANIME_SAVE_DIRECTORY }}   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}

      - name: upload google storge
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ github.event.inputs.path }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK }}:${{ secrets.cloudname }}/202401   ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}
