name: shipin第3次下载rclone上传.yml
on:
  workflow_dispatch:
    inputs:
      path:
        description: '下载路径'
        required: true
        default: 'shipin'

jobs:
  pikpak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create Config'
        run: |
          echo 'username: ${{ secrets.PIKPAKUSERNAME }}
          password: ${{ secrets.PIKPAKPASSWORD }}' >> config.yml
      - name: update
        run: |
           sudo apt-get update >/dev/null 2>&1
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
           tool-cache: true
           android: true
           dotnet: true
           haskell: true
           large-packages: true
           docker-images: false
           swap-storage: true

      - name: 'Download file from PikPak 3'
        run: |
          chmod a+x pikpakcli
          ./pikpakcli download -c 10 -p ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_3 }}

      - name: upload onedrive 3
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ${{ secrets.VIDEO_NINE_DOWNLOAD_PATH_3 }}/  ${{ secrets.TO_UPLOAD_TO_THE_NETDISK_ONEDRIVE }}:${{ secrets.YEARS }}/${{ secrets.VIDEO_PP_SAVE_DIRECTORY }}  ${{ secrets.RCLONE_UPLOAD_CONFIGURATION_PARAMETERS }}

      - name: 开启新的下载任务
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: shipin第4次下载rclone上传.yml
          ref: main

      - name: 删除旧的上传记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
